version: 0.2

phases:
  install:
    runtime-versions:
      node: 12
  build:
    commands:
      - echo Nothing to do yet

artifacts:
  files:
    - index.html
    - favicon.ico
    - styles/*
    - images/*
